apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      serviceAccountName: open-webui
      containers:
        - name: ollama
          image: ollama/ollama:latest
          env:
          - name: HOME
            value: "/app"
          - name: DATA_DIR
            value: "/app/.ollama"
          ports:
          - containerPort: 11434
          resources: {}
          #  requests:
          #    cpu: "16"
          #    memory: "50Gi"
          #  limits:
          #    cpu: "32"
          #    memory: "100Gi"
          #    nvidia.com/gpu: "0"
          volumeMounts:
          - name: ollama-data
            mountPath: /app/.ollama
          tty: true
        - name: open-webui
          image: ghcr.io/open-webui/open-webui:main
          env:
            #- name: GOOGLE_PSE_ENGINE_ID
            #  valueFrom:
            #    secretKeyRef:
            #      name: open-webui-google-pse
            #      key: google_pse_engine_id
            #- name: GOOGLE_PSE_API_KEY
            #  valueFrom:
            #    secretKeyRef:
            #      name: open-webui-google-pse
            #      key: google_pse_api_key
            - name: ENABLE_SIGNUP
              value: "true"
            - name: AIOHTTP_CLIENT_TIMEOUT
              value: '30'
            - name: ENABLE_OLLAMA_API
              value: "true"
            - name: WEBUI_AUTH
              value: "false"
            - name: ENABLE_RAG_WEB_SEARCH
              value: "true"
            - name: RAG_WEB_SEARCH_ENGINE
              #value: "google_pse"
              value: duckduckgo
            - name: OPENAI_API_BASE_URL
              value: "https://mixtral-mixtral-serve.apps.ocp-beta-test.nerc.mghpcc.org/v1"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mixtral-vllm-key
                  key: api_key
            # UPDATE THIS and uncomment
            - name: WEBUI_URL
              value: "http://open-webui-open-webui.apps.ocp-beta-test.nerc.mghpcc.org"
            - name: OLLAMA_BASE_URL
              value: "http://0.0.0.0:11434"
            - name: HOME
              value: "/app"
            - name: DATA_DIR
              value: "/app/.ollama"
          ports:
            - containerPort: 8080
          resources: {}
          #  requests:
          #    cpu: "16"
          #    memory: "50Gi"
          #  limits:
          #    cpu: "32"
          #    memory: "100Gi"
          #    nvidia.com/gpu: "0"
          volumeMounts:
            - name: ollama-data
              mountPath: /app/.ollama
            - name: openwebui-data
              mountPath: /app/backend/data
      volumes:
        - name: ollama-data
          persistentVolumeClaim:
            claimName: ollama-pvc
        - name: openwebui-data
          persistentVolumeClaim:
            claimName: open-webui-pvc

