apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: open-webui-scc-binding
  namespace: open-webui
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
  - kind: ServiceAccount
    name: open-webui
    namespace: open-webui
